<a href="https://colab.research.google.com/github/divya0620/Machine-learning-practice/blob/main/dept_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({
    'Roll_No': [201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211],
    'Name': ['Liam', 'Olivia', 'Noah', 'Emma', 'Ava',
             'William', 'Sophia', 'James', 'Isabella', 'Mason', 'Mia'],

    'Department': ['CSE', 'CSE', 'HR', 'HR', 'CSE',
                   'Finance', 'Finance', 'HR', 'CSE', 'Finance', 'HR'],

    'Age': [19, 20, 21, 22, 20, 23, 21, 22, 19, 24, 20],
    'Math': [78, 85, 88, 90, 76, 84, 79, 92, 87, 81, 75],
    'Science': [82, 89, 91, 86, 80, 88, 83, 94, 90, 85, 77]
})

print(df)

    Roll_No      Name Department  Age  Math  Science
0       201      Liam        CSE   19    78       82
1       202    Olivia        CSE   20    85       89
2       203      Noah         HR   21    88       91
3       204      Emma         HR   22    90       86
4       205       Ava        CSE   20    76       80
5       206   William    Finance   23    84       88
6       207    Sophia    Finance   21    79       83
7       208     James         HR   22    92       94
8       209  Isabella        CSE   19    87       90
9       210     Mason    Finance   24    81       85
10      211       Mia         HR   20    75       77

In [ ]:
df['Total'] = df['Math'] + df['Science']
print(df)

    Roll_No      Name Department  Age  Math  Science  Total
0       201      Liam        CSE   19    78       82    160
1       202    Olivia        CSE   20    85       89    174
2       203      Noah         HR   21    88       91    179
3       204      Emma         HR   22    90       86    176
4       205       Ava        CSE   20    76       80    156
5       206   William    Finance   23    84       88    172
6       207    Sophia    Finance   21    79       83    162
7       208     James         HR   22    92       94    186
8       209  Isabella        CSE   19    87       90    177
9       210     Mason    Finance   24    81       85    166
10      211       Mia         HR   20    75       77    152

In [ ]:
df.drop('Science', axis=1, inplace=True)

print(df)

    Roll_No      Name Department  Age  Math  Total
0       201      Liam        CSE   19    78    160
1       202    Olivia        CSE   20    85    174
2       203      Noah         HR   21    88    179
3       204      Emma         HR   22    90    176
4       205       Ava        CSE   20    76    156
5       206   William    Finance   23    84    172
6       207    Sophia    Finance   21    79    162
7       208     James         HR   22    92    186
8       209  Isabella        CSE   19    87    177
9       210     Mason    Finance   24    81    166
10      211       Mia         HR   20    75    152

In [ ]:
pivot_dept = df.pivot_table(
    index='Department',
    values='Total',
    aggfunc='mean'
)

print(pivot_dept)

                 Total
Department
CSE         166.750000
Finance     166.666667
HR          173.250000

In [ ]:
df.groupby('Department')['Total'].mean()

Department
CSE        166.750000
Finance    166.666667
HR         173.250000
Name: Total, dtype: float64

In [ ]:
df_missing = df.copy()

df_missing.loc[2, 'Math'] = np.nan
df_missing.loc[7, 'Total'] = np.nan

print(df_missing)

df_missing.isnull()

    Roll_No      Name Department  Age  Math  Total
0       201      Liam        CSE   19  78.0  160.0
1       202    Olivia        CSE   20  85.0  174.0
2       203      Noah         HR   21   NaN  179.0
3       204      Emma         HR   22  90.0  176.0
4       205       Ava        CSE   20  76.0  156.0
5       206   William    Finance   23  84.0  172.0
6       207    Sophia    Finance   21  79.0  162.0
7       208     James         HR   22  92.0    NaN
8       209  Isabella        CSE   19  87.0  177.0
9       210     Mason    Finance   24  81.0  166.0
10      211       Mia         HR   20  75.0  152.0

    Roll_No   Name  Department    Age   Math  Total
0     False  False       False  False  False  False
1     False  False       False  False  False  False
2     False  False       False  False   True  False
3     False  False       False  False  False  False
4     False  False       False  False  False  False
5     False  False       False  False  False  False
6     False  False       False  False  False  False
7     False  False       False  False  False   True
8     False  False       False  False  False  False
9     False  False       False  False  False  False
10    False  False       False  False  False  False

In [ ]:
df.loc[0:4, ['Name', 'Department', 'Total']]

df.loc[df['Department'] == 'CSE']

   Roll_No      Name Department  Age  Math  Total
0      201      Liam        CSE   19    78    160
1      202    Olivia        CSE   20    85    174
4      205       Ava        CSE   20    76    156
8      209  Isabella        CSE   19    87    177

In [ ]:
grouped = df.groupby('Department')

grouped['Total'].mean()
grouped['Math'].sum()

Department
CSE        326
Finance    244
HR         345
Name: Math, dtype: int64

In [ ]:
multi_index_df = df.groupby(['Department', 'Name'])['Total'].mean()
print(multi_index_df)

Department  Name
CSE         Ava         156.0
            Isabella    177.0
            Liam        160.0
            Olivia      174.0
Finance     Mason       166.0
            Sophia      162.0
            William     172.0
HR          Emma        176.0
            James       186.0
            Mia         152.0
            Noah        179.0
Name: Total, dtype: float64

In [ ]:
multi_index_df.loc['CSE']
multi_index_df.loc[('HR', 'Noah')]

np.float64(179.0)